name: ci
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Show version
        run: |
          git symbolic-ref --quiet --short HEAD 2>/dev/null
          git rev-list --count HEAD

      - name: Bump version and push tag
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ env.github-token }}
          tag: 1.2.3-preview
          dry_run: true

