name: ci
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Show version
        run: |
          git symbolic-ref --quiet --short HEAD 2>/dev/null
          git rev-list --count HEAD

      - name: Create tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: 1.2.3-preview
        run: |
          gh release create "$tag" --repo="$GITHUB_REPOSITORY" --title="${tag}" --generate-notes
