name: Manual Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: "new release/tag"
        required: true
jobs:
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Show version
        run: |
          git status
          git symbolic-ref --quiet --short HEAD 2>/dev/null
          git rev-list --count HEAD

      # - name: Create tag
      #   run: git tag ${{ github.event.inputs.version }}; git tag --list; git push origin tag ${{ github.event.inputs.version }}

      # - name: Try powershell
      #   shell: pwsh
      #   run: ./build/build.ps1 -Directory abc -Version 1.2.3

  non-build:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Show message
        run: echo "this is not main branch, ${{ github.ref }}"

  share-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Version
        id: generate-version
        shell: pwsh
        run: |
          . ./build/build.ps1
          $Version = Get-Version
          Write-Output "RELEASE_VERSION=$Version" >> $GITHUB_OUTPUT

      - name: Receive Version
        run: echo "version= ${{ steps.generate-version.outputs.RELEASE_VERSION }}"
